packages:
  - '.'

catalog:
  '@tailwindcss/vite': 'latest'
  '@tanstack/react-query': 'latest'
  '@types/node': 'latest'
  '@types/react': 'latest'
  '@types/react-dom': 'latest'
  '@vitejs/plugin-react': 'latest'
  'class-variance-authority': 'latest'
  'clsx': 'latest'
  'framer-motion': 'latest'
  'lucide-react': 'latest'
  'react': 'latest'
  'react-dom': 'latest'
  'tailwind-merge': 'latest'
  'tailwindcss': 'latest'
  'vite': 'latest'
  'zod': 'latest'